config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :edit, :update, :create, :destroy] do
    resources :doses, only: [:new, :create ]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, :through => :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :template => 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  # def set_cocktail
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>New Cocktail</h1>

<div class="form-main">
  <div class="form-container">
  <p>Please update name & photo</p>
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, :label => "Insert a cocktail photo",  as: :file %>
  <%= f.submit class:"btn-ghost new-btn" %>

  <% end %>
  </div>
    <div class="back-button">
    <%= link_to :back do %>
    <i class="fas fa-chevron-left"></i>

    <% end %>
  </div>
  </div>
    <br>

  <br>

  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/cocktails/index.html.erb
<div class="home-banner">
 <div class="navbar navbar-lewagon fixed-top">


      <div class="nav-item active">
       <%= link_to "Home", root_path, class: "nav-link" %>
    </div>
     </div>


  <h1> <strong>It's Cocktailicoussssss</strong> </h1>
  <p>
  <span id="banner-typed-text"></span>
</p>


</div>
<div id="center-btn">
 <%=link_to" Create a new cocktail ", new_cocktail_path, :class => "btn btn-ghost" %>
</div>

<!-- <h1 >Browse through your favourite cocktails!</h1> -->
<div class="container">
<div class="cards">

  <%@cocktails.each do |cocktail|%>
  <%if cocktail.photo.attachment.nil? %>
  <div class="card-category" style="background-color:orange">
    <%else%>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
      <% end %>
      <%=link_to cocktail.name, cocktail_path(cocktail) %> | <%=link_to cocktail_path(cocktail), method: :delete,
      data: { confirm: "Do you really want to delete this cocktail?"} do %>
      <i class="far fa-trash-alt"></i>
      <% end %>

    </div>
  <%end%>

</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
<h1>New Cocktail</h1>
<p>Please insert the name and a photo of the cocktails you would like to add.</p>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>

<% end %>

</div>

app/views/cocktails/show.html.erb
<div class="container">
 <p> <%= link_to "return to all cocktails", cocktails_path %> </p>
  <h1><%=@cocktail.name%></h1>
  <%= link_to "Edit cocktail", edit_cocktail_path(@cocktail), class: "btn-ghost new-btn" %> | <%=link_to cocktail_path(@cocktail), method: :delete,
      data: { confirm: "Do you really want to delete this cocktail?"} do %>
      <i class="far fa-trash-alt"></i>
      <% end %>
<br>
  <div class="flexbox">
    <div class="box">
  <div id="cocktail_img">

    <% if @cocktail.photo.attachment.nil? %>
      <p> No Image has been uploaded for this cocktail </p>
    <% else %>
      <%= cl_image_tag @cocktail.photo.key, height: 280, width: 300, crop: :fill, id: "cocktail_image" %>

    <%end%>
  </div>

</div>
<div class="box">

    <h4 class="headline-font">Ingredients:</h4>
  <% if @cocktail.doses.nil? %>
  Add ingredients to this cocktail
  <% else %>
    <ul>
      <% @cocktail.doses.each do |dose| %>
      <li>  <%= dose.description%> of <%=dose.ingredient.name %></li>
      <p> <%=link_to "delete", dose_path(dose), method: :delete,
      data: { confirm: "Do you really want to delete this cocktail?"} %>
    </p>
    <% end %>
    <% end %>
  </ul>

</div>
</div>

<div class="form-main show-form">
  <div class="form-container show-form">
    <h4 class="headline-font">Add an ingredient:</h4>

    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <!-- [...] -->
    <!-- [...] -->
    <%= f.submit "add", class: "btn-ghost show-btn" %>
    <% end %>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "add", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i|Raleway:100,300,400,500,600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>




    <%= yield %>

</div>

<div class="footer">
  <div class="footer-links">
    <%= link_to "https://github.com/AnnaHerzog", :target => "_blank" do %>
    <i class="fab fa-github"></i>
    <%end%>
     <%= link_to "https://www.facebook.com/annaHerzog92", :target => "_blank" do %>
    <i class="fab fa-facebook"></i>
    <%end%>
       <%= link_to "https://www.linkedin.com/in/annaherzog/", :target => "_blank" do %>
    <i class="fab fa-linkedin"></i>
    <%end%>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> from Berlin.
  </div>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
_navbar.html.erb